<a href="https://colab.research.google.com/github/sreeparvathitk/python-projects/blob/main/dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data = {"Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],"Name": ["Anu", "Rahul", "Meera", "Arjun", "Sneha", "Vishnu", "Diya", "Adithya"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT"],
    "Age": [25, 28, 30, 26, 32, 29, 27, 31],
    "Salary": [35000, 55000, 60000, 48000, 45000, 40000, 52000, 65000],
    "City": ["Kochi", "Calicut", "Kannur", "Kochi", "Trivandrum", "Kochi", "Kannur", "Calicut"]
}
df = pd.DataFrame(data)
print(df)

   Employee_ID     Name Department  Age  Salary        City
0          101      Anu         HR   25   35000       Kochi
1          102    Rahul         IT   28   55000     Calicut
2          103    Meera    Finance   30   60000      Kannur
3          104    Arjun         IT   26   48000       Kochi
4          105    Sneha         HR   32   45000  Trivandrum
5          106   Vishnu      Sales   29   40000       Kochi
6          107     Diya    Finance   27   52000      Kannur
7          108  Adithya         IT   31   65000     Calicut

In [4]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [5]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Salary', 'City'], dtype='object')

In [10]:
for i in df.columns:
 print(i)

Employee_ID
Name
Department
Age
Salary
City

In [11]:
df.dtypes

Employee_ID     int64
Name           object
Department     object
Age             int64
Salary          int64
City           object
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  8 non-null      int64
 1   Name         8 non-null      object
 2   Department   8 non-null      object
 3   Age          8 non-null      int64
 4   Salary       8 non-null      int64
 5   City         8 non-null      object
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes

In [13]:
df.select_dtypes(include= 'number')

   Employee_ID  Age  Salary
0          101   25   35000
1          102   28   55000
2          103   30   60000
3          104   26   48000
4          105   32   45000
5          106   29   40000
6          107   27   52000
7          108   31   65000

In [14]:
df.values

array([[101, 'Anu', 'HR', 25, 35000, 'Kochi'],
       [102, 'Rahul', 'IT', 28, 55000, 'Calicut'],
       [103, 'Meera', 'Finance', 30, 60000, 'Kannur'],
       [104, 'Arjun', 'IT', 26, 48000, 'Kochi'],
       [105, 'Sneha', 'HR', 32, 45000, 'Trivandrum'],
       [106, 'Vishnu', 'Sales', 29, 40000, 'Kochi'],
       [107, 'Diya', 'Finance', 27, 52000, 'Kannur'],
       [108, 'Adithya', 'IT', 31, 65000, 'Calicut']], dtype=object)

In [15]:
df.axes

[RangeIndex(start=0, stop=8, step=1),
 Index(['Employee_ID', 'Name', 'Department', 'Age', 'Salary', 'City'], dtype='object')]

In [16]:
df.ndim

2

In [17]:
df.size

48

In [18]:
df.shape

(8, 6)

In [19]:
df.memory_usage()

Index          132
Employee_ID     64
Name            64
Department      64
Age             64
Salary          64
City            64
dtype: int64

In [24]:
df1=df.drop("Age",axis=1)
df1

   Employee_ID     Name Department  Salary        City
0          101      Anu         HR   35000       Kochi
1          102    Rahul         IT   55000     Calicut
2          103    Meera    Finance   60000      Kannur
3          104    Arjun         IT   48000       Kochi
4          105    Sneha         HR   45000  Trivandrum
5          106   Vishnu      Sales   40000       Kochi
6          107     Diya    Finance   52000      Kannur
7          108  Adithya         IT   65000     Calicut

In [25]:
df.head(4)

   Employee_ID   Name Department  Age  Salary     City
0          101    Anu         HR   25   35000    Kochi
1          102  Rahul         IT   28   55000  Calicut
2          103  Meera    Finance   30   60000   Kannur
3          104  Arjun         IT   26   48000    Kochi

In [26]:
df.tail(3)

   Employee_ID     Name Department  Age  Salary     City
5          106   Vishnu      Sales   29   40000    Kochi
6          107     Diya    Finance   27   52000   Kannur
7          108  Adithya         IT   31   65000  Calicut